on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

name: Copy Distribution
jobs:
  copy:
    name: Copy to registry
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Update values
        run: |
          docker pull rtrompier/distribution:v2-sha-extension
          docker tag rtrompier/distribution:v2-sha-extension ghcr.io/huggingface/distribution-v2/distribution:v2-sha-extension
          docker push ghcr.io/huggingface/distribution-v2/distribution:v2-sha-extension
